Added __repr__ to make help display commands properly
khazhyk/discord.py pull request #2
Opened 2019-05-12 12:38 UTC by MinerChAI

### Summary

### Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2019-05-12 19:41 UTC, khazhyk commented on discord/ext/commands/default.py
> +
Please don't add this extra whitespace

2019-05-12 20:01 UTC, MinerChAI commented on discord/ext/commands/default.py
> +
Ok
Btw its pep8

2019-05-12 20:54 UTC, khazhyk commented
I know, please follow the existing style in discord.py, not pep8

On Sun, May 12, 2019, 13:01 John Meow <notifications@github.com> wrote:

> *@MinerChAI* commented on this pull request.
> ------------------------------
>
> In discord/ext/commands/default.py
> <https://github.com/khazhyk/discord.py/pull/2#discussion_r283151927>:
>
> >  class Channel(CustomDefault):
>      """Default parameter which returns the channel for this context."""
>
>      async def default(self, ctx, param):
>          return ctx.channel
>
> +
>
> Ok
> Btw its pep8
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/khazhyk/discord.py/pull/2#discussion_r283151927>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AALYPCIV3NAMXBPQYX73N7TPVBZTLANCNFSM4HMKIZFA>
> .
>

2019-05-13 06:53 UTC, MinerChAI commented on discord/ext/commands/default.py
> +
And there were three of them

2019-05-13 12:28 UTC, MinerChAI commented
@khazhyk can mege now

2019-05-14 07:00 UTC, khazhyk requested changes
Please squash into a single commit too

2019-05-14 07:00 UTC, khazhyk commented on discord/ext/commands/default.py
> +
here too

2019-05-14 07:00 UTC, khazhyk commented on discord/ext/commands/default.py
> +
you missed a spot

2019-05-14 07:00 UTC, khazhyk commented on docs/ext/commands/commands.rst
> +    async def echo_image(ctx, *, image: Image = LastImage):
There's no need to copy paste the whole example, either explain in the above section and put the example there, or cut this down to just the class header for LastImage (which is the only difference)

2019-05-15 14:01 UTC, MinerChAI commented
Fixed now @khazhyk

2019-05-19 23:29 UTC, khazhyk commented
Rebased into 4d183f40effbabf8a975817873674cd36c5c3cee

2019-05-19 23:29 UTC, closed without merging